### ISSUE TITLE
Scroll behavior of hamburger menu?

### ISSUE THREAD

**Issue by gruiz17** [HanaHaus/HanaHaus-app#54]
So I see these two specs for the hamburger menu on mobile:

![hhintro](https://cloud.githubusercontent.com/assets/2757082/6454249/3b869410-c0fc-11e4-9992-d6c1c34fe1cf.png)

and 

![hhmenu](https://cloud.githubusercontent.com/assets/2757082/6454252/46586b98-c0fc-11e4-88bd-fe623c52e930.png)

But what happens in between? what sort of transition do we want when the user scrolls to the work/learn/play section from the main image?

**Comment by ssdesign** [comment]
Hi,
Two things.

Firstly, I have not updated the mobile design yet, but please follow the color scheme of the website (eg. White instead of Black overlay etc.)

Secondly, the transition should be something like what Ben showed an example the other day, a smooth sliding with a slight bounce as the screen transitions from one to the next.

**Comment by gruiz17** [comment]
1) What bg color should I use for the header at the bottom instead of white? I'm currently using #f2f2f2 grey.

2) I'll find a way to do this, thanks!

**Comment by ssdesign** [comment]
1) #f2f2f2 is OK to use.
